Начинаем программировать
htmlacademy-ecmascript/1752255-cinemaddict-16 pull request #2
Opened 2021-11-24 13:52 UTC by 34comeOn

2021-11-24 19:46 UTC, ArtemVeremienko requested changes
Всё хорошо! 
С основными моментами справился, молодец 💪 
Нужно перенести некоторые зависимости в нужное место, смотри комментарий ниже 🙂

2021-11-24 19:46 UTC, ArtemVeremienko commented on package.json
> +    "webpack-dev-server": "4.4.0"
Почему решил их добавить в `dependencies`?

Все эти зависимости нужно установить в зависимости для разработки. Они не понадобятся в итоговой сборке 🙂 Давай их туда переместим с помощью команды `npm i <package>@<version> -ED`

2021-11-25 13:40 UTC, 34comeOn commented on package.json
> +    "webpack-dev-server": "4.4.0"
Да, ошибочка вышла)

2021-11-25 15:00 UTC, ArtemVeremienko approved these changes
Отлично, идём дальше! 😉

2021-11-25 15:36 UTC, merged