Module2 task1
htmlacademy-ecmascript/1752255-cinemaddict-16 pull request #4
Opened 2021-12-07 18:18 UTC by 34comeOn

2021-12-08 13:13 UTC, ArtemVeremienko requested changes
Всё хорошо структурированно и лакончино, молодец!

Не совсем понял подхода по написанию стрелочных функций с возвратом значения в скобках, почему решил выбрать такой формат записи?
```js
const func = () => (
  doSome();
);
```

Давай добавим немного больше универсального кода и всё будет готово 😉

2021-12-08 13:13 UTC, ArtemVeremienko commented on src/mock/task.js
> +);
Хорошее решение через `Array.from` 👍

2021-12-08 13:13 UTC, ArtemVeremienko commented on src/util.js
> +};
Вариант хороший, так как мы уже подключили `day.js`, можешь попробовать с помощью него это сделать.

2021-12-08 13:13 UTC, ArtemVeremienko commented on src/mock/task.js
> +const getGenre = () => {
Эту функцию можно заменить на больее универсальную, которая будет принимать массив элементов и возвращать случайный массив, то есть не будем привязываться только к жанрам.

2021-12-09 12:17 UTC, 34comeOn commented on src/mock/task.js
> +);
Не знал, что можно без скобок передать функцию)

2021-12-09 20:44 UTC, ArtemVeremienko requested changes
Осталось добавить последние штрихи и готово 😉

2021-12-09 20:44 UTC, ArtemVeremienko commented on src/util.js
> +const getBoolean = () => (Boolean(getRandomInteger(0,1)));
Лучше явно назвать, что мы получаем случайное булевое значение `getRandomBoolean`

2021-12-09 20:44 UTC, ArtemVeremienko commented on src/util.js
> +};
Так как мы ожидаем случайный элемент из всего массива, то уже известны мин и макс. То есть можно упростить до:

```suggestion
const getRandomArrayElement = (array) => array[getRandomInteger(0, array.length)];
```

И после этого можно удалить все `*_MAX_INDEX` константы.

2021-12-10 05:09 UTC, 34comeOn commented on src/util.js
> +};
Красота!)

2021-12-10 13:38 UTC, ArtemVeremienko approved these changes

2021-12-10 13:38 UTC, merged