3.10. Революция или эволюция? (часть 1)
htmlacademy-ecmascript/1752255-cinemaddict-16 pull request #5
Opened 2021-12-16 13:07 UTC by 34comeOn

2021-12-16 21:45 UTC, ArtemVeremienko requested changes
В целом всё хорошо сделано, молодец 💪 
Есть несколько мелких замечаний:

1. Логика всех функций для созданий темплейтов `createSomeTemplate` должны переместиться в геттер `template`, чтобы всё было внутри класса. Пример можешь посмотреть в `src/view/comments-view.js` снизу.

2. Все компоненты лучше помещать в константы, даже если мы их используем только один раз. Они могут понадобиться в дальнейшем и так их будет проще искать. Можно их сгруппировать, например:

- импорты
- константы
- html элементы
- компоненты
- остальной код

2021-12-16 21:45 UTC, ArtemVeremienko commented on src/view/comments-view.js
> +  }
Лучше вернуть уже готовую вёрстку, чтобы весь функционал был в нашем классе компонента:
```suggestion
  get template() {
    const {emotion, comment, author} = this.#currentComments;
    return `<li class="film-details__comment">
  <span class="film-details__comment-emoji">
    <img src="./images/emoji/${emotion}.png" width="55" height="55" alt="emoji-smile">
  </span>
  <div>
    <p class="film-details__comment-text">${comment}</p>
    <p class="film-details__comment-info">
      <span class="film-details__comment-author">${author}</span>
      <span class="film-details__comment-day">${getReleaseDate().format('DD MMMM YYYY')}</span>
      <button class="film-details__comment-delete">Delete</button>
    </p>
  </div>
</li>`;
  }
```

2021-12-16 21:45 UTC, ArtemVeremienko commented on src/main.js
> +render(headerElement, new ProfileRatingView(alreadyWatchedMovies.length).element, RenderPosition.BEFOREEND);
создание компонентов лучше выносить в переменные, они могут нам в дальнейшем понадомиться и нам не придётся пересоздавать их (DRY)
```suggestion
const profileRatingView = new ProfileRatingView(alreadyWatchedMovies.length);
render(headerElement, profileRatingView .element, RenderPosition.BEFOREEND);
```

Исправь все остальные создания компонентов по такому примеру.

2021-12-18 16:31 UTC, 34comeOn commented on src/view/comments-view.js
> +  }
А на Лайве лектор говорил, что лучше оставить разметку в функции. Сделаю, как ты советуешь)

2021-12-18 19:05 UTC, ArtemVeremienko commented on src/view/comments-view.js
> +  }
@34comeOn здесь особой разницы пока нет. Интересено, в чём было обоснование оставлять разметку в функции? не помнишь примерный тайминг где об этом говорилось?

2021-12-18 19:06 UTC, ArtemVeremienko approved these changes

2021-12-18 19:06 UTC, merged

2021-12-19 13:28 UTC, 34comeOn commented on src/view/comments-view.js
> +  }
Третий Лайв 59 минута.