Разделяй и властвуй
htmlacademy-ecmascript/1752255-cinemaddict-16 pull request #6
Opened 2022-01-10 13:27 UTC by 34comeOn

2022-01-10 20:33 UTC, ArtemVeremienko requested changes
В жанре фильма выводиться несколько категорий https://prnt.sc/26c6x3i и из-за этого ломается сетка карточек. Нужно сделать вывод как в шаблоне https://prnt.sc/26c6x9t

2022-01-10 20:33 UTC, ArtemVeremienko commented on src/view/film-card-view.js
> +    this._callback.editClick(isCurrentMovie);
Не совсем понял, какая у нас здесь логика и для чего. Объясни подробнее, пожалуйста.

2022-01-10 20:46 UTC, ArtemVeremienko commented on src/main.js
> +  }
Циклы где нам не нужны индесксы лучше делать через `for..of`
```suggestion
  for (let currentComment of currentComments) {
    const filmCommentViewComponent = new FilmCommentView(currentComment);
    render(filmCommentsContainer, filmCommentViewComponent, RenderPosition.AFTERBEGIN);
  }
```

2022-01-10 20:48 UTC, ArtemVeremienko commented on src/main.js
> +  }
или метод `forEach`
```suggestion
  currentComments.forEach((comment) => {
    const filmCommentViewComponent = new FilmCommentView(comment);
    render(filmCommentsContainer, filmCommentViewComponent, RenderPosition.AFTERBEGIN);
  })
```

2022-01-11 09:06 UTC, 34comeOn commented on src/view/film-card-view.js
> +    this._callback.editClick(isCurrentMovie);
Не правильно назвал эту функцию, лучше назвать не isCurrentMovie, а compairMovieId. Эта функция для сравнения текущего значения id фильма с фильмами из массива movies. Этот поиск нужен, чтобы передать индекс фильма в класс PopupView.

2022-01-11 20:16 UTC, ArtemVeremienko approved these changes
Всё отлично исправил, молодец!

Не могу понять почему тебе нравится функции стрелки оборачивать в скобки

 ```js
    const compairMovieId = (movie) => (
      movie.id === this.#movies.id
    );
```

они компактнее смотрятся в одну строку
```js
const const compairMovieId = (movie) => movie.id === this.#movies.id;
```

или если нравится блоком записывать, то тогда через фигурные скобки
 ```js
    const compairMovieId = (movie) => {
      return movie.id === this.#movies.id
    };
```
но небольшие функции лучше смотряться в одну строку 😉

2022-01-11 20:19 UTC, merged